[portfolio]
user = portfolio
group = portfolio

listen = /run/php/php-fpm-portfolio.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = ondemand
pm.max_children = 5
pm.process_idle_timeout = 10s
pm.max_requests = 200

php_admin_value[open_basedir] = /var/www/portofolio:/tmp
php_admin_value[upload_max_filesize] = 10M
php_admin_value[post_max_size] = 12M
php_admin_value[memory_limit] = 128M
php_admin_value[expose_php] = Off
php_admin_flag[display_errors] = off
php_admin_value[error_log] = /var/www/portofolio/storage/logs/php-fpm.log
php_admin_flag[log_errors] = on
